# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd095377699e3cfc096e894ecba758f32560fb329e524e187e03f5b01954eb71484bca5aaf1cd1827c5399f6e1427f92d9c06a5dc70fa35cff8a225ea2ce8b2

test:
  secret_key_base: 3a52494393614c104ddef952837ed2ab62231fc458fb423933e6e068c36467faf778afd986ad9001a1b318fccab77719061b3e6722480e13dde95c6d3b7f4480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
